### ISSUE TITLE
Same version number as the Linux-ProcDump

### ISSUE THREAD

**Issue by theuserbl** [microsoft/ProcDump-for-Mac#4]
Currently the Linux-ProdDump have version 3.3 from May, 28.
And the Mac-ProcDump have version 1.0 from November, 11.

So the binary of the Mac-ProcDump is newer and have the newes changes included.

I think it is hard to compare the versions, if they are in the future still different. Which will be newer 7.3 of the Mac-ProcDump or 10.5 of the Linux-ProcDump?

In this case I hope, that the Linux and Mac binaries will be in the future published on the same time with the same version number.
For example, that the next version for the Linux-ProcDump and the Mac-ProcDump will be 4.0 or so.

Edit:
I think the best way would be to rename the ProcDump-for-Linux repo to ProcDump-for-Unix.
And there can then be published the binaries for Linux **_and_** Mac.
And then they can be published on the same time with the same version number.

**Comment by MarioHewardt** [comment]
Thank you for your feedback! We decided to use version 1.0 for the Mac release for similar reasons as when we launched the Linux version. While the Windows version was already at version 9 or 10 at the time, the Linux and Mac versions are conceptually the same tool—a trigger-based dump generator—but have distinct feature sets and may never achieve full feature parity. For example, the Linux version includes unique triggers not found in Windows, and the Mac version will likely follow a similar path. Aligning the version numbers could create confusion about the availability of features across platforms, so we opted for a fresh start with 1.0 to clearly differentiate the platform-specific capabilities.
